Update  seyon.user set retired = 0 where retired =1 and iduser > 1;
Update  seyon.login set retired = 0 where retired =1 and idlogin > 1;
Update  seyon.project set retired = 0 where retired =1 and idproject > 1;
Update  seyon.address set retired = 0 where retired =1 and idaddress > 1;
Update  seyon.bill set retired = 0 where retired =1 and idbill > 1;
Update  seyon.drawing set retired = 0 where retired =1 and iddrawing > 1;
Update  seyon.payment set retired = 0 where retired =1 and idpayment > 1;
Update  seyon.history set retired = 0 where retired =1 and idhistory > 1;
Update  seyon.document set retired = 0 where retired =1 and iddocument > 1;